language: swift
osx_image: xcode10.2
branches:
  only:
    - master
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install specific_install
  - gem specific_install -l https://github.com/ladeiko/Generamba.git
  - brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
  - brew install XcodeGen    
  - pod repo update  
jobs:
  default:
    script:
      - cd Demo && make default
  alert:
    script:
      - cd Demo && make alert
