before_install:
- gem install specific_install
- gem specific_install -l https://github.com/ladeiko/Generamba.git
- brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
- brew install XcodeGen
os: osx
osx_image: xcode9.4
language: swift
script:
- cd Demo && make
