name: Demo
options:
  bundleIdPrefix: com.test
targets:
  Demo:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - Sources
      - Models
    dependencies:
      - target: DemoTests
    scheme:
      testTargets:
        - DemoTests
    settings:
      INFOPLIST_FILE: Info.plist
  DemoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources
        excludes:
          - "Sources/AppDelegate.swift"
          - "Sources/*.storyboard"
